### ISSUE TITLE
Release Feature Checklist

### ISSUE THREAD

**Issue by ClayHanson** [ClayHanson/BlocklandRebuilt-IssueBoard#177]
- [x] Implement PUBLIC BRICKS
- [x] Implement loading bricks without a client present
- [x] Implement 'lives' and 'default minigame' into minigames system
- [x] Implement authentication server messages
- [x] Disable mirrors by default, add option on the client to let the user re-enable if they wish
