### ISSUE TITLE
Hotloading Checklist

### ISSUE THREAD

**Issue by ClayHanson** [ClayHanson/BlocklandRebuilt-IssueBoard#195]
The new add-on hot-loading feature has some kinks to be worked out.

- [x] Executing an Item add-on will disconnect everyone when it's equipped.
- [x] Hashes are sometimes inserted into the manifest in a corrupted state.
- [x] addExtraResource seems to regenerate the manifest everytime it's called(?).
- [x] Fix not being able to hotload Interiors

### Metadata:
 - Game Version: `v0.22`
