### ISSUE TITLE
Rebuilt Plate Problems Checklist

### ISSUE THREAD

**Issue by Kenkoman** [ClayHanson/BlocklandRebuilt-IssueBoard#217]
Let's list all of the current issues with the Rebuilt Plate here, to keep track of them.

- [x] Some sky presets load as completely dark environments (Confirmed fixed!)
- [x] Precipitation does not work (Confirmed fixed!)
- [x] Sun Elevation does not work
- [x] The "Shadow Color" option probably does nothing now and can be removed/hidden
- [x] Sun Flare color does not work
- [x] Only the first and third sun flare textures work
- [x] Sky color does not work
- [x] Water Scroll Y cannot be reset to 0
- [x] Water and underwater colors alpha channel cannot be changed (Confirmed fixed!)
- [x] Water add-ons with `$Water::kill` set in the `.water` file (such as the default `Water_Lava`) do not damage you
- [x] Placeholder map image needs replacing
- [x] No death message for water death
- [x] Sun flare is still shown if the sun flare color is set to black
- [x] Water scroll is visually incorrect when switching between Simple and Advanced mode
