### ISSUE TITLE
Localization Checklist

### ISSUE THREAD

**Issue by consoleSkunk** [ClayHanson/BlocklandRebuilt-IssueBoard#381]
### English localization issues
- [x] Brick box hint (`UI_PLAYGUI_USE_BRICKS_TOOLTIP`) incorrectly reads `Press 1 or  2 3 4 5 6 7 8 9 0 or           to use bricks`.
- [x] "Remap Failed" error (`UI_OPTIONS_REMAP_FAILED`) is incorrectly "REMAP FILED"

### Translation key issues
- [x] Brick selector favorites button's translation key is incorrectly `UI_BSD_BTN_SET_FAVS` (which doesn't exist) instead of `UI_COMMON_BTN_SET_FAVS`
- [x] `UI_OPTIONS_REMAP_FAILED` is incorrectly used for the message as well instead of `UI_OPTIONS_BOUND_TO_NON_MAPPABLE_CMD`
- [x] "Load Add-Ons?" popup incorrectly uses `UI_MAINMENU_CHANGEKEY_TITLE` instead of `UI_MAINMENU_AUTH_LOADADDONS_TITLE`
- [x] Many default strings are still missing their translation keys
  - [x] Bot Hole GUI
  - [x] Add-Ons GUI (without RTB)
  - [x] wrenchDlg
  - [x] wrenchEventsDlg

### Localization support TODO list
- [x] Changing languages should actually save your choice
- [x] GuiPopUpCtrl
- [x] GuiTextListCtrl
- [x] GuiCheckBoxCtrl (Add a text popup on hover)

### Unicode issues
- [x] `chatWhiteListFilter()` is stripping UTF-8 components, mangling Unicode text
- [x] Fallback fonts doesn't appear in chat if they're not sent by your client

### Implementation bugs
- [x] UI elements that use bitmaps such as `demoBanner.png` are incorrectly scaled: 
[Screenshot_2023-09-22_14-59-31](https://github.com/ClayHanson/BlocklandRebuilt-IssueBoard/assets/50500602/22884ee0-b347-49b1-91c6-9b2913c386b1)

### Metadata:
 - Game Version: `v2-rev2181`

**Comment by consoleSkunk** [comment]
from a quick glance over the `allClientsGuis.gui` file, here's all the GUIs that remain:

- [x] MessageBoxOKCancelDlg
- [x] HelpDlg
- [x] NetGraphGui
- [x] TrustInviteGui
- [x] MiniGameInviteGui
- [x] JoinServerPassGui
- [x] connectingGui
- [x] ManualJoin
- [x] changeMapGui
- [x] unBanGui
- [x] BrickManGui
- [x] PSD_Window
- [x] LoadBricksColorGui (only technically because our RTB has a setting for it)
- [x] saveBricksWarningGui
- [x] newMessageHud ("SAY" and "TEAM" channel names are hardcoded)
- [x] SelectNetworkGui
- [x] defaultControlsGui
- [x] SavingGui
- [x] ColorSetGui (avatar editor colorset)

### Mission Editor related
- [ ] InspectDlg
- [ ] InspectAddFieldDlg
- [ ] LoadFileDlg
- [ ] SaveFileDlg

### B4v21 additions
- [x] newColorGui
- [x] GmAddonsGui (already mentioned in OP)
- [x] EnvGui

### Unused (i.e. don't worry about these ones)
- [ ] ConsoleDlg (window title is hidden behind the console output)
- [ ] recordingsDlg (unused since v12)
- [ ] AutoUpdateGui (unused since v20)
- [ ] fastLoadWarningGui
- [ ] demoBrickLimitGui (unused since Rebuilt v1.8)
